# Generated by Django 5.0.6 on 2024-08-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_childprofile_birth_height_parentprofile_parentno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
