# Generated by Django 5.0.6 on 2024-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_childprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
