# Generated by Django 5.0.8 on 2024-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_childprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('batch_number', models.CharField(max_length=6)),
                ('date_manufacture', models.DateField()),
                ('expiry_date', models.DateField()),
                ('age_group', models.CharField(max_length=50)),
                ('doses', models.IntegerField()),
                ('indications', models.TextField()),
                ('stock', models.IntegerField()),
                ('free_or_paid', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=4)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
