# Generated by Django 5.1 on 2024-08-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vaccinerequesthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineDose',
            fields=[
                ('dose_id', models.AutoField(primary_key=True, serialize=False)),
                ('dose_number', models.IntegerField()),
                ('date_administered', models.DateField(blank=True, null=True)),
                ('interval_days', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_doses', to='app.vaccine')),
            ],
        ),
    ]
