# Generated by Django 5.1 on 2024-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_vaccinedose_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinedose',
            name='interval_days',
            field=models.CharField(max_length=50),
        ),
    ]
