# Generated by Django 5.1 on 2024-08-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_vaccinedose_interval_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='doses',
        ),
    ]
