# Generated by Django 5.1 on 2024-08-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_vaccine_doses'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerequest',
            name='dose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vaccinedose'),
        ),
        migrations.AddField(
            model_name='vaccinerequesthistory',
            name='dose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vaccinedose'),
        ),
    ]
