# Generated by Django 5.1 on 2024-08-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notes',
        ),
    ]
