# Generated by Django 5.1.1 on 2024-09-06 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
        ),
    ]
