# Generated by Django 5.1.1 on 2024-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_notification_related_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, verbose_name='Age')),
                ('main_heading', models.CharField(max_length=255, verbose_name='Main Heading')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
