# Generated by Django 5.1.1 on 2024-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_feedingchart'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='mental_health_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
