# Generated by Django 5.0.6 on 2024-07-07 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('parent', 'Parent'), ('healthcare_provider', 'Healthcare Provider')], max_length=20)),
                ('address', models.TextField()),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
